s = set()
n = input("enter a number: ")
s.add(n)
n = input("enter a number: ")
s.add(n)
n = input("enter a number: ")
s.add(n)
n = input("enter a number: ")
s.add(n)
n = input("enter a number: ")
s.add(n)
n = input("enter a number: ")
s.add(n)

print(s)